version: 0.2
name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

phases:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        sudo apt-get install python3 -y
        sudo apt install supervisor -y
        python3 -m pip install --upgrade pip
        python3 -m pip install --user virtualenv
        
    - name: mystep
      run: |
        sudo mkdir usr/local/bin/basicforms
        sudo cp -a $(pwd) /usr/local/bin/basicforms
        cd usr/local/bin/basicforms
        virtualenv venv
        source venv/bin/activate
        pip3 install django
        pip3 install gunicorn
        deactivate
        sudo cp gunicorn_supervisor.conf /etc/supervisor/conf.d
        sudo supervisorctl update
        sudo supervisorctl reload
        
        


    # - location
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
