version: 0.2
name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

phases:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --user virtualenv
    - name: mystep
      run: |
        python -m venv myenv
        source myenv/bin/activate
        pip install django
        python manage.py runserver


    # - location
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths: